aprilweilab/grgl

src/calculations.cpp, src/calculations.h, src/grgp.cpp, src/util.h
Samples are specified by a text file, one ID per line. Right now it uses numerical ID, not the (e.g.) VCF string identifier.
Mutations are specified via range, currently.
=> Add sample/mutation subset support for allele frequency

CMakeLists.txt, include/grgl/mut_iterator.h, pygrgl/clicmd/construct.py, src/build_shape.cpp, src/build_shape.h, src/gconverter.cpp, src/grgl.cpp, src/mut_iterator.cpp, src/util.h, test/unit/test_construct.cpp, test/unit/test_util.cpp, test/unit/testing_utilities.h
* Add new argument to "grg construct", add unit tests
* "grg construct --population-ids <file:field>" now attaches populations to the data.
* Add population ID map support to grgl executable
* Set populationID on the sample nodes based on the individual IDs.
* Unit tests for the population ID handling in GRG construction and the associated helper functions.
* Add individual ID support to MutationIterator
* Add individual filtering to gconverter
=> Add population support to GRG samples

include/grgl/grg.h, src/grg_helpers.h, src/grgp.cpp, src/python/_grgl.cpp, src/serialize.cpp
The API has a flag that loads them by default, but users can choose. All of the calculations we have implemented only need up edges if you are doing sample-based subset queries.
=> Only reconstruct "Up edges" when necessary

src/gconverter.cpp
`gconverter` now supports `-e` flag to remove variants that are empty.
=> Optionally remove empty variants during file conversion

third-party/picovcf/picovcf.hpp
This adds support for IGD v4, which is slightly smaller than IGD v3.
=> Upgrade to new (backwards-compatible) picovcf version

src/build_shape.cpp
std::hash<size_t> just returns the value. The bloom filters do better with some randomness, so we use the hash_combine function with a non-zero seed.
=> Fix the hashing from the previous PR

CMakeLists.txt, include/grgl/grg.h, include/grgl/mutation.h, include/grgl/serialize.h, src/grg.cpp, src/grg_helpers.h, src/python/_grgl.cpp, src/serialize.cpp
Serialize mutations using getMutationsToNodeOrdered() which ensures that the MutationID order matches the (position, allele) sort order upon deserialization. If you have an "old" GRG that does not have sorted MutationIDs, just reserialize it:
`./grgl old.grg -o new.grg`
Make down edges optional on deserialization, just like up edges are.
Compile-time support for gperf CPU profiling in the CMakeList. Just download the appropriate release of gperf source, build it, and then build grgl with -DENABLE_CPU_PROF=ON
A GRG can be checked for mutation ID ordering via
mutationsAreOrdered() (C++) and mutations_are_ordered (Python).
=> Order mutation IDs, down edges optional, gperf support

include/grgl/ts2grg.h, pygrgl/clicmd/convert.py, src/grgl.cpp, src/ts2grg.cpp
Conversion from TS to GRG previously ignored topology changes below a mutation _IF_ that topology change did not impact the sample set of the mutation. This manifests when the break and join point of a recombination both occur entirely below a mutation.
You can now run `grg convert --maintain-topo` if you want to instead retain such topology changes. The algorithm change is quite simple: instead of traversing from added/removed edges to their MRCA we instead just traverse all the way to the root(s). The nodes along the way are marked to be split next time they are encountered by a mutation.
On a reasonably large Tree-Seq file (500k samples, 100Mbp len), there is no noticeable timing difference between the two versions of the algorithm.
GRG file size is pretty much the same as well; when …
=> Add --maintain-topo and --no-simplify options to grg convert

README.md, setup.py
Pip has removed --install-option. Use environment variables instead to specify build options. This is somewhat cleaner anyways, because the options are specified identically for pip and bdist_wheel.
=> Use ENV instead of pip --install-options

Dockerfile, doc/python_api.rst, include/grgl/grg.h, src/calculations.cpp, src/grg.cpp, src/python/_grgl.cpp, test/endtoend/run_tests.py, test/unit/test_grg.cpp
See the API documentation for details. This is a fast, simple way to perform computations on a GRG. Integrated with numpy. On a medium-sized GRG (600MB) this allows you to do allele frequency in 0.42 seconds instead of 48 seconds.
In the future, we may want to add these features:
* Restrict to genome range
* Restrict to sample subset
* Compute multiple values via windows
=> Add dot-product API

DEVELOPING.md, README.md, doc/conf.py, setup.py
Highlight that `pygrgl` can now be installed directly from PyPi.
=> Reorg some markdown content, fix RTD project name

src/python/_grgl.cpp
There are now two APIs for getting the node->mutation mapping:
1. get_node_mutation_pairs(): ordered by nodeID
2. get_mutation_node_pairs(): ordered by mutationID (which is ordered by (position, allele))
The latter is very helpful when looking at per-region or in-order calculations on the graph.
=> Add get_mutation_node_pairs API to Python (ordered by mutation)

src/grg.cpp
The dotProduct() API always does a full graph traversal using the node ID ordering (topologically sorted). Previously, when doing an upward traversal it used the down-edges to propagate values, and when doing a downward traversal it used up-edges to propagate values. Now it uses down-edges for both: the downward traversal has to "push" values to its children instead of "pulling" values from its parents.
This turns out to be about 25% faster than the previous way, but the main reason to change this is that the down edges are what is stored on disk, and loading the up-edges essentially doubles the memory usage.
=> Dot-product _always_ uses down edges (even in downward direction)

include/grgl/grg.h, src/calculations.cpp, src/map_mutations.cpp
When we reach a root, and that root covers all the necessary muts, add it to the candidate set.
=> Fix bug that was producing extra root nodes during MapMutations

.clang-format, include/grgl/mutation.h
Should be using C++-style casts anyways.
=> Use C++-style cast to avoid clang-format issue

doc/cpp_api.rst, doc/ts_convert.rst, include/grgl/ts2grg.h, pygrgl/clicmd/convert.py, src/calculations.cpp, src/grg_helpers.h, src/grgl.cpp, src/python/_grgl.cpp, src/ts2grg.cpp
* Fairly efficient algorithm for counting the number of individuals that coalesce at each node, during the conversion from tree-seq to GRG. It "forgets" individual list information as quickly as possible in an effort to save RAM.
* Add some additional checks on the tree-sequence samples and individuals to make sure they conform to the GRG assumptions. We can theoretically handle tree-seqs where there are non-leaf samples, but only if those samples are parents of samples all the way down (e.g., the last "layer" of the trees is all samples). In the future we may want a way to flag non-leafy samples.
* Fix some issues with the allele freq output when there are multiple copies of the same mutation.
=> Add coalescence counting for TS->GRG conversion

doc/python_api.rst, include/grgl/grg.h, include/grgl/grgnode.h, src/common_visitors.h, src/grg.cpp, src/python/_grgl.cpp, test/unit/test_grg.cpp
* New Python API `shared_frontier()` traverses in a direction from a given list of seed nodes and collects any nodes that are reachable from all seeds on the current path. All paths are searched. If a path has no nodes that are shared by all seeds, then no nodes from that path will be output in the frontier. Useful for queries of small sets of (highly similar) nodes, as it can be on the order of microseconds instead of milliseconds for the equivalent use-case with `matmul()`.
* `matmul()` has a new `emit_all_nodes` parameter, which when set will make the output rows be values for all nodes, instead of just the samples or mutations (depending on direction). The input is still a vector of sample/mutation values.
* Topological search now has a sparse and dense version. The sparse version is …
=> shared_frontier() API, matmul(emit_all_nodes=True), improve topo

doc/examples_and_applications.rst, include/grgl/grg.h, pygrgl/clicmd/split.py, src/grgl.cpp, src/python/_grgl.cpp, src/util.h, test/endtoend/test_basic.py
`grg split` changes:
* Can specify what directory to put the resulting split GRGs into.
* Can specify  a number of arbitrary ranges to split with. Right now has to be base-pair coordinates (cM is unimplemented).
=> Add "-o" flag to "grg split"

include/grgl/common.h, include/grgl/grg.h, include/grgl/internal_mult.h, src/python/_grgl.cpp, test/unit/test_mult.cpp
Using a smaller numpy datatype saves memory and also speeds up computation. For general "counting" computation, you cannot use anything smaller than numpy.int32 because a GRG can have up to (2**32)-2 nodes in the graph. However, in special cases the int16 and int8 could be useful.
One special case that is useful is the boolean problem, where the input as a vector with a single 1 and the rest are zeros. This can be used to explicitly retrieve thegenotype matrix, for example. In this case, we only need boolean values, and matmul now stores all node values packed into a bitvectors.
=> matmul() support for smaller datatypes, including bitvectors

include/grgl/grg.h, include/grgl/internal_mult.h, src/python/_grgl.cpp, test/endtoend/test_matmul.py
`matmul(init=...)` option lets you specify how node values are accumulated during matrix multiplication. The default `init=None` initializes all node values to `0`, which gives the "standard" matrix multiplication behavior of each node value `v(n) = sum(v(c) for all c in children)`.
However, if you give initialization values to nodes this becomes:
`v(n) = init(n) + sum(v(c) for all c in children)`
There are three ways to initialize:
1. `init="xtx"` initializes all nodes with two times their coalescence count. A bottom-up multiplication of `1_n` using this option will produce the product `X.T * X` (used for GWAS).
2. `init=numpy.array([1, 1, 0, ... ])` initializes all nodes to a single value for each multiplication row. An easier way to think about this is to consider an input matrix of …
=> Node initialization option for `matmul()`

include/grgl/mut_iterator.h, src/mut_iterator.cpp, third-party/picovcf/picovcf.hpp
Use the new binary search feature of the IGD index to find the location for creating the partial GRG (tGRG). This can speedup construction significantly for large datasets.
Thousand genomes chromosome 22 builds about 3x faster. The way we build this dataset uses a ton of trees, which each need to seek to the right location, so this is an edge case for sure (most won't be 3x faster).
50k individuals stdpopsim dataset is only about 15% faster, which makes sense.
=> Upgrade picovcf and perform fast seeking to genome ranges

include/grgl/common.h, include/grgl/grg.h, include/grgl/mut_iterator.h, src/build_shape.cpp, src/grg_helpers.h, src/mut_iterator.cpp, src/python/_grgl.cpp, src/serialize.cpp, test/endtoend/test_basic.py
An unphased GRG is identical to a phased GRG, except that the is_phased flag is set to False, and the haplotypes cannot be interpreted. Individual-based computations (e.g., matmul() with by_individual=True) should be identical between phased and unphased graphs.
Right now, some limitations:
1. Construction is slow. We stick all heterozygous alleles on the first copies of the individual, which makes the haplotypes not very similar across samples.
2. Similarly, the size of the GRG can be large. An unphased GRG can be up to 5x larger than the phased GRG for the same data.
3. BGEN is not supported for unphased input. The way the encode the data is complex, so deferring for now.
=> Initial support for unphased GRGs

src/grg_helpers.h, src/python/_grgl.cpp, test/endtoend/test_modify.py
Previously if you gave an empty filter list, it would just copy the GRG. Now it does nothing, and returns False.
=> Make save_subset() more robust to misspecified filters

doc/python_api.rst, src/python/_grgl.cpp, test/endtoend/test_basic.py
Useful for when treating a GRG like a matrix. The default direction is assumed to be "UP", which means the matrix is NxM.
=> Add helpers grg.shape and grg.haploid_shape

README.md, include/grgl/common.h, include/grgl/csr_storage.h, include/grgl/file_vector.h, include/grgl/grg.h, include/grgl/grgnode.h, include/grgl/serialize.h, src/fast_build.cpp, src/grg.cpp, src/grg_helpers.h, src/python/_grgl.cpp, src/serialize.cpp, test/endtoend/test_basic.py, test/unit/test_common.cpp, test/unit/test_csr_storage.cpp
Backwards-compatible file format change. Previously the CSR arrays were stored with 32-bit indices, which limited the number of edges that a GRG could have. They now use 64-bit indices.
Put some hard constraints around node creation, and add unit tests for these edge cases.
=> Increase number of supported edge to >trillions
